version: '3.8'

services:
  # Application FastAPI
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - monitoring
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/items_db
    depends_on:
      - db

  # Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: items_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - "9090:9090"
    networks:
      - monitoring

volumes:
  postgres_data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge